### ISSUE TITLE
libiberty.a compiled to x86 arch instead of PPC in ${PS3DEV}/ppu/lib

### ISSUE THREAD

**Issue by daschewie** [ps3dev/ps3toolchain#63] opened 2013-04-07 16:17 UTC
For some reason the latest ps3toolchain is placing an x86 version of libiberty.a into the ppu/lib and spu/lib directories. The other files in the directory seem to be PPC files as expected. I rebuilt my toolchain twice trying to fix it.

Steps to reproduce:
- run ps3toolchain scripts
- cd ${PS3DEV}/ppu/lib
- ar xvf libiberty.a
- file strncmp.o

Expected:
strncmp.o: ELF 64-bit MSB relocatable, 64-bit PowerPC or cisco 7500, version 1 (SYSV), not stripped

Actual:
strncmp.o: ELF 32-bit LSB relocatable, Intel 80386, version 1 (SYSV), not stripped

Environment:
Linux Mint 14/VMWare

**Comment by wargio** [comment] 2020-06-29 08:30
gcc 7.2.0 does this too. i can confirm.

**Comment by zeldin** [comment] 2020-06-29 12:45
Well, libiberty is a library used by the toolchain itself, so I don't know whether or not it's expected to get a target version of it at all.
In my case I get target libraries (ppc64) in ${PS3DEV}/ppu/lib, and host libraries (aarch64 in this case) in ${PS3DEV}/ppu/lib64, so they are separate.  But it seems building on a 32-bit system gives you this conflation issue.

**Comment by zeldin** [comment] 2020-06-29 14:33
The other host library installed is `libcc1.so.0.0.0`.  It doesn't look like any of the toolchain binaries are actually linked against it though...

**Comment by zeldin** [comment] 2020-06-29 14:41
I think both of these are meant for gcc plugins.

**Comment by wargio** [comment] 2020-06-30 08:07
well it should not be installed on ppu then.

**Comment by zeldin** [comment] 2020-06-30 08:30
No.  But neither should the stuff in ${PS3DEV}/ppu/bin.  So there is no direct correlation between "exists under ${PS3DEV}/ppu" and "should be installed on ppu".  But I agree that host libs and target libs should not be installed in the same directory.  Possibly we don't need to install the host libs on the build host at all.

**Comment by wargio** [comment] 2020-06-30 08:31
yes i agree. i'll do some tests just to be sure.

**Comment by zeldin** [comment] 2020-06-30 08:46
Actually, I don't think there should be any target libraries in ${PS3DEV}/ppu/lib anymore, so this shouldn't be an issue. ${PS3DEV}/ppu is the prefix for the cross compiler, so the normal directory structure would be

${PS3DEV}/ppu/bin       host binaries
${PS3DEV}/ppu/lib{,64} host libraries
${PS3DEV}/ppu/powerpc64-ps3-elf/lib{,64} target libraries

then to this we add

${PS3DEV}/pslight/ppu/lib   target libraries
${PS3DEV}/portlibs/ppu/lib  target libraries

but we never put any target libraries in ${PS3DEV}/ppu/lib.  PSL1GHT used to do that, but doesn't anymore.  So ${PS3DEV}/ppu/{bin,lib,lib64} should be strictly host now.

**Comment by wargio** [comment] 2020-06-30 08:48
ok, then it should be fine because the files i have are in the folder you just mentioned.
i think we can close this then.

**Comment by zeldin** [comment] 2020-06-30 08:53
Well, I can check if disabling plugins makes gcc not create ${PS3DEV}/ppu/lib{,64} at all, just to reduce the amount of confusion on this point.  I don't think anyone actually needs plugins.  :smile:

**Comment by wargio** [comment] 2020-06-30 08:54
ok, i'll check this thread once you have a "fix" just to rebuild the toolchain and see if it "fixes" the issue.

**Comment by zeldin** [comment] 2020-06-30 15:58
@wargio `libcc1.so` was simple to get rid of, but boy do the GNU people love their iberty...  binutils, gcc and gdb _each_ install `libiberty.a`, and it can't be disabled with configure options without breaking the build.  So I hade to fudge it.  But now the deed is done -- no host libraries in ${PS3DEV}/ppu/lib{,64} anymore.

**Closed by zeldin** 2020-06-30 15:58 UTC

**Comment by wargio** [comment] 2020-06-30 16:08
i'll test this just to be sure, but thanks :D

**Comment by wargio** [comment] 2020-07-01 16:57
i can confirm that works as expected @zeldin
