### ISSUE TITLE
Could not build the tool chain 404 not found, 302 moved temporarily

### ISSUE THREAD

**Issue by james28909** [ps3dev/ps3toolchain#115] opened 2021-11-15 09:41 UTC
everything was going pretty smooth and then all of the sudden it wasnt going so smooth. imagine that! XD

looks like it is just some files hosted in these links. not sure if there are more because build stops there

` /usr/bin/install -c -m 644 ../cjpeg.1 ../djpeg.1 ../jpegtran.1 ../rdjpgcom.1 ../wrjpgcom.1 '/usr/local/ps3dev/portlibs/ppu/share/man/man1'
make[1]: Leaving directory '/home/james/ps3toolchain/build/ps3libraries/build/jpeg-8b/build-ppu'
--2021-11-15 04:36:15--  http://download.savannah.gnu.org/releases/freetype/freetype-2.4.3.tar.gz
Resolving download.savannah.gnu.org (download.savannah.gnu.org)... 209.51.188.200, 2001:470:142:5::200
Connecting to download.savannah.gnu.org (download.savannah.gnu.org)|209.51.188.200|:80... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: http://download-mirror.savannah.gnu.org/releases/freetype/freetype-2.4.3.tar.gz [following]
--2021-11-15 04:36:15--  http://download-mirror.savannah.gnu.org/releases/freetype/freetype-2.4.3.tar.gz
Resolving download-mirror.savannah.gnu.org (download-mirror.savannah.gnu.org)... 209.51.188.200, 2001:470:142:5::200
Reusing existing connection to download.savannah.gnu.org:80.
HTTP request sent, awaiting response... 404 Not Found
2021-11-15 04:36:15 ERROR 404: Not Found.

../scripts/004-freetype-2.4.3.sh: Failed.
../scripts/009-ps3libraries.sh: Failed.
ERROR: Could not run the toolchain script.`

**Comment by zeldin** [comment] 2021-11-15 11:01
Duplicate of #112

**Closed by zeldin** 2021-11-15 11:01 UTC
